#!/usr/bin/env ruby
require 'logger'

LOGGER = Logger.new(STDOUT)

def execute(cmd, fail_silently = false)
  LOGGER.debug("Executing -- #{cmd}")
  output = `#{cmd}`
  LOGGER.debug(output) if output.length > 0
  if !fail_silently && !$?.success?
    raise "Failed with exit status #{Integer($?.exitstatus)}"
  end
  output
end

HOME = `echo ${HOME}`.chomp
PACKAGES_PATH = "#{HOME}/Library/Application Support/Sublime Text 3/Packages"
USER_SETTINGS_PATH = File.join(PACKAGES_PATH, 'User')
BACKUP_USER_SETTINGS_PATH = "#{USER_SETTINGS_PATH}.backup"
SAVED_SETTINGS_PATH = File.join(File.dirname(File.expand_path(__FILE__)), 'User')

LOGGER.info('***************************')
LOGGER.info('*Installing Sublime Text...')
LOGGER.info('***************************')

execute("brew cask install sublime-text", fail_silently: true)

LOGGER.info("*Setting up package directory")
execute("mkdir -p '#{PACKAGES_PATH}'")

LOGGER.info("*Backing up user settings")
execute("cp -r '#{USER_SETTINGS_PATH}' '#{BACKUP_USER_SETTINGS_PATH}'", fail_silently: true)

LOGGER.info("*Removing current user settings")
execute("rm -r '#{USER_SETTINGS_PATH}'")

LOGGER.info("*Symlinking saved settings from")
execute("ln -s '#{SAVED_SETTINGS_PATH}' '#{USER_SETTINGS_PATH}'")

LOGGER.info('*Done!')
