#!/usr/bin/env ruby

require 'logger'

LOGGER = Logger.new(STDOUT)

def execute(cmd, fail_silently = false)
  LOGGER.debug("Executing -- #{cmd}")
  output = `#{cmd}`
  LOGGER.debug(output) if output.length > 0
  if !fail_silently && !$?.success?
    raise "Failed with exit status #{Integer($?.exitstatus)}"
  end
  output
end

LOGGER.info('**********************')
LOGGER.info('*Installing iterm2...')
LOGGER.info('**********************')

execute { `brew cask install iterm2` } rescue

LOGGER.info('*Symlinking iterm settings to ~/.iterm...')
this_dir = File.dirname(File.expand_path(__FILE__))
ITERM_SETTINGS = File.join(this_dir, 'settings')
HOME = `echo ${HOME}`.chomp
execute("rm '#{HOME}/.iterm'")
execute("ln -s '#{ITERM_SETTINGS}' '#{HOME}/.iterm'")

LOGGER.info('*Done!')

LOGGER.info(
  'To complete setup, configure the settings in the iterm application to' \
  'point to the ~/.iterm directory.'
)
LOGGER.info('Please refer to README.md for further instructions.')
