#!/usr/bin/env ruby
require 'logger'

LOGGER = Logger.new(STDOUT)

def execute(cmd, fail_silently = false)
  LOGGER.debug("Executing -- #{cmd}")
  output = `#{cmd}`
  LOGGER.debug(output) if output.length > 0
  if !fail_silently && !$?.success?
    raise "Failed with exit status #{Integer($?.exitstatus)}"
  end
  output
end

execute("brew install antigen", fail_silently: true)

LOGGER.info('*Symlinking zsh files to ~/.zshdir...')
ZSH_DIR = File.dirname(File.expand_path(__FILE__))
HOME = `echo ${HOME}`.chomp

execute("rm '#{HOME}/.zshdir'", fail_silently: true)
execute("ln -s '#{ZSH_DIR}' '#{HOME}/.zshdir'")
