#!/usr/bin/env ruby
require 'logger'

LOGGER = Logger.new(STDOUT)

def execute(cmd, fail_silently = false)
  LOGGER.debug("Executing -- #{cmd}")
  output = `#{cmd}`
  LOGGER.debug(output) if output.length > 0
  if !fail_silently && !$?.success?
    raise "Failed with exit status #{Integer($?.exitstatus)}"
  end
  output
end

LOGGER.info('*Installing wistia-dub...')
execute("brew tap wistia/dub git@github.com:wistia/dub.git")
execute("brew install wistia-dub", fail_silently: true)

LOGGER.info('*Finish setup as described in the README -- https://github.com/wistia/dub/blob/master/README.md')
